name: "Install Yandex Cloud CLI"
description: "Installs Yandex Cloud CLI for interaction with Yandex Cloud"
inputs:
  oauthToken:
    description: "Yandex Cloud OAuth token"
    required: false
runs:
  using: "composite"
  steps:
    - name: Download and install Yandex Cloud CLI
      shell: bash
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
        export PATH=$HOME/yandex-cloud/bin:$PATH
        source $GITHUB_PATH
        source ~/.bashrc
        which yc
        yc --version

    - name: Set OAuth token
      shell: bash
      if: ${{inputs.oauthToken != ''}}
      env:
        YC_OAUTH_TOKEN: ${{ inputs.oauthToken }}
      run: |
        yc config set token $YC_OAUTH_TOKEN
